const Data = [
  {
    id: 1,
    title: "Tesla Homepage Clone",
    stack: "React FrontEnd",
    tech: ["html","css", "react", "javascript", "sass"],
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "./ProjectImages/teslaclone.png",
    github: "https://github.com/Akshay26953/Tesla-Clone-FrontEnd",
    link: "https://tesla-clone-7ff99.web.app/",
  },
  {
    id: 2,
    title: "Booking App",
    tech: ["react","javascript" ,"html","css", "mongodb" , "nodejs","express"],
    stack: "MERN Stack",
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "./ProjectImages/bookingapp.png",
    github: "https://github.com/Akshay26953/Booking-App-MERN-Project",
    // link: "http"
  },
  {
    id: 3,
    title: "To Do List",
    tech: ["html", "css", "javascript"],
    stack: "Vanilla JS",
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "./ProjectImages/todo.png",
    github: "https://github.com/Akshay26953/To-Do-List",
    link: "https://akshay26953.github.io/To-Do-List/",
  },
  {
    id: 4,
    title: "Like Post",
    tech: ["html", "css", "javascript"],
    stack: "Vanilla JS",
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "./ProjectImages/likepost.png",
    github: "https://github.com/Akshay26953/Like-Post",
    link: "https://akshay26953.github.io/Like-Post/",
  },
  {
    id: 5,
    title: "Calculator",
    tech: ["html", "css", "javascript"],
    stack: "Vanilla JS",
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "./ProjectImages/calculator2.png",
    github: "https://github.com/Akshay26953/Calculator2",
    link: "https://akshay26953.github.io/Calculator2/",
  },
  {
    id: 6,
    title: "Weather App",
    tech: ["html", "css", "javascript"],
    stack: "Vanilla JS",
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "./ProjectImages/weatherapp.png",
    github: "https://github.com/Akshay26953/Weather-App",
    link: "https://akshay26953.github.io/Weather-App/",
  },
  {
    id: 7,
    title: "USA City Data",
    tech: ["html", "css", "javascript"],
    stack: "Vanilla JS",
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "https://raw.githubusercontent.com/Akshay26953/Portfolio-Website/main/public/ProjectImages/bookingapp.PNG",
    // image: "./ProjectImages/usadata.png",
    github: "https://github.com/Akshay26953/US-State-Data",
    link: "https://akshay26953.github.io/US-State-Data/",
  },
  {
    id: 8,
    title: "My Projects",
    tech: ["html","css", "react", "javascript", "sass"],
    stack: "React FrontEnd",
    defaultImg: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
    image: "./ProjectImages/myproject.png",
    // github: "https://github.com/Akshay26953/US-State-Data",
    link: "https://my-projects-5a53e.web.app/",
  },
];

export default Data;
